version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=PROD
      - DB_HOST=database
      - DB_USER=psql
      - DB_PASSWORD=pass
      - DB_NAME=users
      - DB_PORT=5432
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: psql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
